### PR TITLE
implement port hopping

### PR DESCRIPTION
**Pull request by keakon**

### CODE REVIEW

**Comment by tkizm1** [comment]
要不提到上游[sing](https://github.com/SagerNet/sing)

**Comment by keakon** [comment]
> 要不提到上游[sing](https://github.com/SagerNet/sing)

sing 的开发者曾经拒绝了实现这个功能
https://github.com/SagerNet/sing-box/issues/229#issuecomment-1336082794

而且我本地测试 sing 的客户端无法成功翻墙，没法测试是否修改正确

**Comment by keakon** [comment]
改由 https://github.com/MetaCubeX/quic-go/commit/46c6f7cdf2d1597e9e1ca52d9fc498539ba96a68 和 https://github.com/MetaCubeX/sing-quic/pull/1/commits/343d9f22d51488a0eeb4c45dc9dcf977d20f44eb 实现，不再需要改动 MetaCubeX/sing

**Comment by Sortnz** [comment]
> 
> sing 的开发者曾经拒绝了实现这个功能 [SagerNet/sing-box#229 (comment)](https://github.com/SagerNet/sing-box/issues/229#issuecomment-1336082794)

It appears that contributions to the codebase are encouraged rather than a refusal to implement the requested feature.

> 
> 而且我本地测试 sing 的客户端无法成功翻墙，没法测试是否修改正确

After thoroughly reading your [blog](https://keakon.uk/2024/01/12/%E9%83%BD2024%E5%B9%B4%E4%BA%86%EF%BC%8C%E8%AF%A5%E6%9B%B4%E6%96%B0%E7%BF%BB%E5%A2%99%E6%8A%80%E6%9C%AF%E4%BA%86), I surmise that the lack of support for port hopping is not due to a limitation on the server side.

---
@tobyxdd May I inquire if modifications to the server-side code are necessary to enable port hopping? I am eager to understand the technical requirements.

**Pull request closed without merging**
